<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('productos')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('productos')->insert([
            // --- Entradas (categoria_id = 1) ---
            [
                'nombre' => 'Yaroa Mixta',
                'imagen' => 'productos/1-Yaroa-Mixta.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Yaroa con carne, pollo, queso, mayonesa, k�tchup y salsa especial',
                'precio' => 220.00,
                'precio_compra' => 120.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 50,
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Tostones con Salami',
                'imagen' => 'productos/2-Tostones-con-Salami.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Tostones fritos acompa�ados de salami frito en rodajas',
                'precio' => 150.00,
                'precio_compra' => 60.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 50,
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Ceviche de Pescado',
                'imagen' => 'productos/3-Ceviche-de-Pescado.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Pescado fresco marinado en lim�n con cebolla morada, aj� y cilantro',
                'precio' => 280.00,
                'precio_compra' => 140.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 30,
                'categoria_id' => 1,
            ],
            [
                'nombre' => 'Pastelitos (3 unidades)',
                'imagen' => 'productos/4-Pastelitos--3-unidades-.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Pastelitos de carne o pollo fritos',
                'precio' => 120.00,
                'precio_compra' => 50.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 40,
                'categoria_id' => 1,
            ],

            // --- Platos Fuertes (categoria_id = 2) ---
            [
                'nombre' => 'La Bandera Dominicana',
                'imagen' => 'productos/5-La-Bandera-Dominicana.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Arroz blanco, habichuelas guisadas, carne guisada (res o pollo), ensalada y aguacate',
                'precio' => 350.00,
                'precio_compra' => 160.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 40,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Mang� con Salami y Queso',
                'imagen' => 'productos/6-Mangu-con-Salami-y-Queso.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Mang� de pl�tano verde con salami frito, queso frito, huevo y cebolla escabechada',
                'precio' => 280.00,
                'precio_compra' => 120.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 40,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sancocho de Siete Carnes',
                'imagen' => 'productos/7-Sancocho-de-Siete-Carnes.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Sancocho tradicional con res, cerdo, pollo, longaniza, costilla, pl�tano, yuca y auyama',
                'precio' => 420.00,
                'precio_compra' => 200.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 25,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Pescado Frito Entero',
                'imagen' => 'productos/8-Pescado-Frito-Entero.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Pescado fresco frito acompa�ado de tostones, ensalada y arroz',
                'precio' => 480.00,
                'precio_compra' => 220.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 20,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Chivo Guisado',
                'imagen' => 'productos/9-Chivo-Guisado.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Chivo guisado en su punto con arroz, habichuelas, ensalada y aguacate',
                'precio' => 450.00,
                'precio_compra' => 210.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 20,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Pernil con Arroz',
                'imagen' => 'productos/10-Pernil-con-Arroz.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Pernil de cerdo horneado con arroz, habichuelas y ensalada',
                'precio' => 380.00,
                'precio_compra' => 180.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 25,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Pollo Guisado',
                'imagen' => 'productos/11-Pollo-Guisado.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Pollo guisado con arroz blanco, habichuelas, ensalada y aguacate',
                'precio' => 320.00,
                'precio_compra' => 140.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 40,
                'categoria_id' => 2,
            ],

            // --- Postres (categoria_id = 3) ---
            [
                'nombre' => 'Habichuelas con Dulce',
                'imagen' => 'productos/12-Habichuelas-con-Dulce.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Postre tradicional de habichuelas dulces con leche, coco y especias',
                'precio' => 110.00,
                'precio_compra' => 50.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 30,
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Flan de Caramelo',
                'imagen' => 'productos/13-Flan-de-Caramelo.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Flan cremoso con caramelo l�quido',
                'precio' => 130.00,
                'precio_compra' => 55.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 30,
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Arroz con Leche',
                'imagen' => 'productos/14-Arroz-con-Leche.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Arroz con leche, canela y pasas',
                'precio' => 90.00,
                'precio_compra' => 35.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 35,
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Tres Leches',
                'imagen' => 'productos/15-Tres-Leches.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Bizcocho ba�ado en tres leches con merengue',
                'precio' => 150.00,
                'precio_compra' => 65.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 20,
                'categoria_id' => 3,
            ],

            // --- Bebidas (categoria_id = 4) ---
            [
                'nombre' => 'Jugo de Chinola Natural',
                'imagen' => 'productos/16-Jugo-de-Chinola-Natural.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Jugo natural de chinola (fruta de la pasi�n)',
                'precio' => 90.00,
                'precio_compra' => 30.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 50,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Morir So�ando',
                'imagen' => 'productos/17-Morir-Sonando.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Tradicional bebida de jugo de naranja con leche evaporada y hielo',
                'precio' => 100.00,
                'precio_compra' => 35.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 60,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Caf� Santo Domingo',
                'imagen' => 'productos/18-Cafe-Santo-Domingo.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Caf� negro tradicional dominicano',
                'precio' => 60.00,
                'precio_compra' => 20.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 80,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Cerveza Presidente',
                'imagen' => 'productos/19-Cerveza-Presidente.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Cerveza nacional dominicana',
                'precio' => 160.00,
                'precio_compra' => 95.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 18.00,
                'stock' => 100,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Agua Botell�n',
                'imagen' => 'productos/20-Agua-Botellon.jpg',
                'codigo_barras' => null,
                'descripcion' => 'Agua purificada en botell�n',
                'precio' => 40.00,
                'precio_compra' => 15.00,
                'unidad_medida' => 'Unidad',
                'itbis_porcentaje' => 0.00,
                'stock' => 100,
                'categoria_id' => 4,
            ],
        ]);
    }
}
