<?php

namespace Database\Seeders\Full;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ModulosFullSeeder extends Seeder
{
    /**
     * Datos extraídos de solo_inserts.sql — tabla `modulos` (86 filas).
     */
    public function run(): void
    {
        $exists = Schema::hasTable('modulos');
        if (!$exists) {
            return;
        }

        Schema::disableForeignKeyConstraints();
        DB::table('modulos')->truncate();

        $rows = [
            ['id' => 1, 'key' => 'auditoria', 'label' => 'Registro de Auditoría', 'icon' => 'bi-clipboard-check', 'categoria' => 'sistema', 'section' => 'Otros', 'sidebar_route' => 'audit-logs.index', 'sidebar_is_route' => 'audit-logs.*', 'sidebar_exact_route' => 'audit-logs.index', 'sidebar_url' => null, 'sidebar_permission' => 'auditoria.view', 'activo' => 1, 'orden' => 67, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-22 00:04:12'],
            ['id' => 2, 'key' => 'backups', 'label' => 'Copias de Seguridad', 'icon' => 'bi-database-down', 'categoria' => 'sistema', 'section' => 'Otros', 'sidebar_route' => 'backups.index', 'sidebar_is_route' => 'backups.*', 'sidebar_exact_route' => 'backups.index', 'sidebar_url' => null, 'sidebar_permission' => 'backups.view', 'activo' => 1, 'orden' => 68, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 3, 'key' => 'ncf', 'label' => 'Comprobantes (NCF)', 'icon' => 'bi-receipt', 'categoria' => 'sistema', 'section' => 'Otros', 'sidebar_route' => 'ncf.index', 'sidebar_is_route' => 'ncf.*', 'sidebar_exact_route' => 'ncf.index', 'sidebar_url' => null, 'sidebar_permission' => 'ncf.view', 'activo' => 1, 'orden' => 63, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 4, 'key' => 'ecf', 'label' => 'Facturación Electrónica (e-CF)', 'icon' => 'bi-cloud-arrow-up', 'categoria' => 'sistema', 'section' => 'Otros', 'sidebar_route' => 'ecf.index', 'sidebar_is_route' => 'ecf.*', 'sidebar_exact_route' => 'ecf.index', 'sidebar_url' => null, 'sidebar_permission' => 'ecf.view', 'activo' => 1, 'orden' => 64, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 5, 'key' => 'secuencias-ecf', 'label' => 'Secuencias e-CF', 'icon' => 'bi-hash', 'categoria' => 'sistema', 'section' => 'Otros', 'sidebar_route' => 'secuencias-ecf.index', 'sidebar_is_route' => 'secuencias-ecf.*', 'sidebar_exact_route' => 'secuencias-ecf.index', 'sidebar_url' => null, 'sidebar_permission' => 'ecf.manage', 'activo' => 1, 'orden' => 64, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 6, 'key' => 'certificados-digitales', 'label' => 'Certificados Digitales', 'icon' => 'bi-key', 'categoria' => 'sistema', 'section' => 'Otros', 'sidebar_route' => 'certificados-digitales.index', 'sidebar_is_route' => 'certificados-digitales.*', 'sidebar_exact_route' => 'certificados-digitales.index', 'sidebar_url' => null, 'sidebar_permission' => 'ecf.certificados', 'activo' => 1, 'orden' => 64, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 7, 'key' => 'payment-processors', 'label' => 'Métodos de Pago', 'icon' => 'bi-credit-card', 'categoria' => 'configuracion', 'section' => 'Otros', 'sidebar_route' => 'payment-processors.index', 'sidebar_is_route' => 'payment-processors.*', 'sidebar_exact_route' => 'payment-processors.index', 'sidebar_url' => null, 'sidebar_permission' => 'payment-processors.view', 'activo' => 1, 'orden' => 66, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 8, 'key' => 'delivery-companies', 'label' => 'Delivery / Plataformas', 'icon' => 'bi-truck', 'categoria' => 'configuracion', 'section' => 'Otros', 'sidebar_route' => 'delivery-companies.index', 'sidebar_is_route' => 'delivery-companies.*', 'sidebar_exact_route' => 'delivery-companies.index', 'sidebar_url' => null, 'sidebar_permission' => 'delivery-companies.view', 'activo' => 1, 'orden' => 66, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 9, 'key' => 'impresoras', 'label' => 'Impresoras y Plantillas', 'icon' => 'bi-printer', 'categoria' => 'configuracion', 'section' => 'Otros', 'sidebar_route' => 'impresoras.index', 'sidebar_is_route' => 'impresoras.*', 'sidebar_exact_route' => 'impresoras.index', 'sidebar_url' => null, 'sidebar_permission' => 'impresoras.view', 'activo' => 1, 'orden' => 65, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 10, 'key' => 'configuracion-general', 'label' => 'Ajustes / Parámetros', 'icon' => 'bi-gear', 'categoria' => 'configuracion', 'section' => 'Otros', 'sidebar_route' => 'configuracion.index', 'sidebar_is_route' => 'configuracion.*', 'sidebar_exact_route' => 'configuracion.index', 'sidebar_url' => null, 'sidebar_permission' => 'configuracion.view', 'activo' => 1, 'orden' => 60, 'created_at' => '2026-07-01 14:06:37', 'updated_at' => '2026-07-22 00:04:12'],
            ['id' => 11, 'key' => 'dashboard', 'label' => 'Dashboard', 'icon' => 'bi-speedometer2', 'categoria' => 'core', 'section' => 'Otros', 'sidebar_route' => 'dashboard', 'sidebar_is_route' => null, 'sidebar_exact_route' => 'dashboard', 'sidebar_url' => null, 'sidebar_permission' => 'dashboard.view', 'activo' => 1, 'orden' => 0, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 12, 'key' => 'inventario', 'label' => 'Inventario', 'icon' => 'bi-box-seam', 'categoria' => 'core', 'section' => 'Otros', 'sidebar_route' => 'productos.index', 'sidebar_is_route' => 'productos.*', 'sidebar_exact_route' => 'productos.index', 'sidebar_url' => null, 'sidebar_permission' => 'productos.view', 'activo' => 1, 'orden' => 1, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 13, 'key' => 'compras', 'label' => 'Compras', 'icon' => 'bi-cart-check', 'categoria' => 'core', 'section' => 'Otros', 'sidebar_route' => 'compras.index', 'sidebar_is_route' => 'compras.*', 'sidebar_exact_route' => 'compras.index', 'sidebar_url' => null, 'sidebar_permission' => 'compras.view', 'activo' => 1, 'orden' => 2, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 14, 'key' => 'proveedores', 'label' => 'Proveedores', 'icon' => 'bi-truck', 'categoria' => 'core', 'section' => 'Otros', 'sidebar_route' => 'proveedores.index', 'sidebar_is_route' => 'proveedores.*', 'sidebar_exact_route' => 'proveedores.index', 'sidebar_url' => null, 'sidebar_permission' => 'proveedores.view', 'activo' => 1, 'orden' => 3, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 15, 'key' => 'kardex', 'label' => 'Kardex', 'icon' => 'bi-journal-text', 'categoria' => 'core', 'section' => 'Otros', 'sidebar_route' => 'kardex.index', 'sidebar_is_route' => 'kardex.*', 'sidebar_exact_route' => 'kardex.index', 'sidebar_url' => null, 'sidebar_permission' => 'kardex.view', 'activo' => 1, 'orden' => 4, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 16, 'key' => 'listas-precio', 'label' => 'Listas de Precios', 'icon' => 'bi-tags', 'categoria' => 'core', 'section' => 'Otros', 'sidebar_route' => 'listas-precio.index', 'sidebar_is_route' => 'listas-precio.*', 'sidebar_exact_route' => 'listas-precio.index', 'sidebar_url' => null, 'sidebar_permission' => 'listas-precio.view', 'activo' => 1, 'orden' => 5, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 17, 'key' => 'ventas', 'label' => 'Terminal de Ventas', 'icon' => 'bi-cart-plus', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'ventas.create', 'sidebar_is_route' => 'ventas.*', 'sidebar_exact_route' => 'ventas.create', 'sidebar_url' => null, 'sidebar_permission' => 'ventas.create', 'activo' => 1, 'orden' => 10, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 18, 'key' => 'cotizaciones', 'label' => 'Cotizaciones', 'icon' => 'bi-file-earmark-text', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'cotizaciones.index', 'sidebar_is_route' => 'cotizaciones.*', 'sidebar_exact_route' => 'cotizaciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'cotizaciones.view', 'activo' => 1, 'orden' => 11, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 19, 'key' => 'conduces', 'label' => 'Conduces', 'icon' => 'bi-truck', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'conduces.index', 'sidebar_is_route' => 'conduces.*', 'sidebar_exact_route' => 'conduces.index', 'sidebar_url' => null, 'sidebar_permission' => 'conduces.view', 'activo' => 1, 'orden' => 12, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 20, 'key' => 'devoluciones', 'label' => 'Devoluciones', 'icon' => 'bi-arrow-return-left', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'devoluciones.index', 'sidebar_is_route' => 'devoluciones.*', 'sidebar_exact_route' => 'devoluciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'devoluciones.view', 'activo' => 1, 'orden' => 13, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 21, 'key' => 'gastos', 'label' => 'Gastos', 'icon' => 'bi-cash-coin', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'gastos.index', 'sidebar_is_route' => 'gastos.*', 'sidebar_exact_route' => 'gastos.index', 'sidebar_url' => null, 'sidebar_permission' => 'gastos.view', 'activo' => 1, 'orden' => 16, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-09 23:46:54'],
            ['id' => 22, 'key' => 'plantilla-gastos', 'label' => 'Plantillas de Gasto', 'icon' => 'bi-file-earmark-richtext', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'plantilla-gastos.index', 'sidebar_is_route' => 'plantilla-gastos.*', 'sidebar_exact_route' => 'plantilla-gastos.index', 'sidebar_url' => null, 'sidebar_permission' => 'plantilla-gastos.view', 'activo' => 1, 'orden' => 17, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-09 23:46:54'],
            ['id' => 23, 'key' => 'clientes', 'label' => 'Clientes', 'icon' => 'bi-people', 'categoria' => 'clientes', 'section' => 'Otros', 'sidebar_route' => 'clientes.index', 'sidebar_is_route' => 'clientes.*', 'sidebar_exact_route' => 'clientes.index', 'sidebar_url' => null, 'sidebar_permission' => 'clientes.view', 'activo' => 1, 'orden' => 20, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 24, 'key' => 'cobros', 'label' => 'Cuentas por Cobrar', 'icon' => 'bi-wallet2', 'categoria' => 'clientes', 'section' => 'Otros', 'sidebar_route' => 'clientes.cuentas', 'sidebar_is_route' => 'clientes.cuentas*', 'sidebar_exact_route' => 'clientes.cuentas', 'sidebar_url' => null, 'sidebar_permission' => 'cobros.view', 'activo' => 1, 'orden' => 21, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 25, 'key' => 'cajas', 'label' => 'Cajas y Turnos', 'icon' => 'bi-cash-stack', 'categoria' => 'clientes', 'section' => 'Otros', 'sidebar_route' => 'cajas.index', 'sidebar_is_route' => 'cajas.*', 'sidebar_exact_route' => 'cajas.index', 'sidebar_url' => null, 'sidebar_permission' => 'cajas.view', 'activo' => 1, 'orden' => 22, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 26, 'key' => 'sucursales', 'label' => 'Sucursales', 'icon' => 'bi-building', 'categoria' => 'organizacion', 'section' => 'Otros', 'sidebar_route' => 'sucursales.index', 'sidebar_is_route' => 'sucursales.*', 'sidebar_exact_route' => 'sucursales.index', 'sidebar_url' => null, 'sidebar_permission' => 'sucursales.view', 'activo' => 1, 'orden' => 30, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 27, 'key' => 'almacenes', 'label' => 'Almacenes', 'icon' => 'bi-buildings', 'categoria' => 'organizacion', 'section' => 'Otros', 'sidebar_route' => 'almacenes.index', 'sidebar_is_route' => 'almacenes.*', 'sidebar_exact_route' => 'almacenes.index', 'sidebar_url' => null, 'sidebar_permission' => 'almacenes.view', 'activo' => 1, 'orden' => 31, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 28, 'key' => 'lavadero', 'label' => 'Terminal Lavadero', 'icon' => 'bi-droplet', 'categoria' => 'lavadero', 'section' => 'Otros', 'sidebar_route' => 'lavadero.index', 'sidebar_is_route' => 'lavadero.*', 'sidebar_exact_route' => 'lavadero.index', 'sidebar_url' => null, 'sidebar_permission' => 'lavadero.view', 'activo' => 1, 'orden' => 35, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 29, 'key' => 'lavadero-servicios', 'label' => 'Servicios de Lavado', 'icon' => 'bi-card-checklist', 'categoria' => 'lavadero', 'section' => 'Otros', 'sidebar_route' => 'lavadero.servicios.index', 'sidebar_is_route' => 'lavadero.servicios.*', 'sidebar_exact_route' => 'lavadero.servicios.index', 'sidebar_url' => null, 'sidebar_permission' => 'lavadero.servicios', 'activo' => 1, 'orden' => 36, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 30, 'key' => 'lavadero-vehiculos', 'label' => 'Vehículos', 'icon' => 'bi-car-front', 'categoria' => 'lavadero', 'section' => 'Otros', 'sidebar_route' => 'lavadero.vehiculos.index', 'sidebar_is_route' => 'lavadero.vehiculos.*', 'sidebar_exact_route' => 'lavadero.vehiculos.index', 'sidebar_url' => null, 'sidebar_permission' => 'lavadero.vehiculos', 'activo' => 1, 'orden' => 37, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 31, 'key' => 'lavadero-citas', 'label' => 'Citas / Turnos', 'icon' => 'bi-calendar-event', 'categoria' => 'lavadero', 'section' => 'Otros', 'sidebar_route' => 'lavadero.citas.index', 'sidebar_is_route' => 'lavadero.citas.*', 'sidebar_exact_route' => 'lavadero.citas.index', 'sidebar_url' => null, 'sidebar_permission' => 'lavadero.citas', 'activo' => 1, 'orden' => 38, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 32, 'key' => 'lavadero-lavadores', 'label' => 'Lavadores', 'icon' => 'bi-people', 'categoria' => 'lavadero', 'section' => 'Otros', 'sidebar_route' => 'lavadero.lavadores.index', 'sidebar_is_route' => 'lavadero.lavadores.*', 'sidebar_exact_route' => 'lavadero.lavadores.index', 'sidebar_url' => null, 'sidebar_permission' => 'lavadero.lavadores', 'activo' => 1, 'orden' => 39, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 33, 'key' => 'restaurante', 'label' => 'Restaurante (Terminal Mesas)', 'icon' => 'bi-cup-straw', 'categoria' => 'restaurante', 'section' => 'Otros', 'sidebar_route' => 'restaurante.index', 'sidebar_is_route' => 'restaurante.*', 'sidebar_exact_route' => 'restaurante.index', 'sidebar_url' => null, 'sidebar_permission' => 'restaurante.view', 'activo' => 1, 'orden' => 40, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 34, 'key' => 'restaurante-kds', 'label' => 'Pantalla Cocina (KDS)', 'icon' => 'bi-egg-fried', 'categoria' => 'restaurante', 'section' => 'Otros', 'sidebar_route' => 'restaurante.kds.index', 'sidebar_is_route' => 'restaurante.kds.*', 'sidebar_exact_route' => 'restaurante.kds.index', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 41, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 35, 'key' => 'restaurante-reservaciones', 'label' => 'Reservaciones', 'icon' => 'bi-calendar-check', 'categoria' => 'restaurante', 'section' => 'Otros', 'sidebar_route' => 'restaurante.reservaciones.index', 'sidebar_is_route' => 'restaurante.reservaciones.*', 'sidebar_exact_route' => 'restaurante.reservaciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'restaurante.reservaciones', 'activo' => 1, 'orden' => 42, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 36, 'key' => 'restaurante-categorias', 'label' => 'Categorías de Mesa', 'icon' => 'bi-tags', 'categoria' => 'restaurante', 'section' => 'Otros', 'sidebar_route' => 'restaurante.categorias.index', 'sidebar_is_route' => 'restaurante.categorias.*', 'sidebar_exact_route' => 'restaurante.categorias.index', 'sidebar_url' => null, 'sidebar_permission' => 'restaurante.categorias', 'activo' => 1, 'orden' => 43, 'created_at' => '2026-07-01 15:04:08', 'updated_at' => '2026-07-01 15:04:08'],
            ['id' => 37, 'key' => 'reportes-ventas', 'label' => 'Reporte Ventas', 'icon' => 'bi-receipt', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.ventas', 'sidebar_is_route' => 'reportes.ventas*', 'sidebar_exact_route' => 'reportes.ventas', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 50, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 38, 'key' => 'reportes-compras', 'label' => 'Reporte Compras', 'icon' => 'bi-cart-check', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.compras', 'sidebar_is_route' => 'reportes.compras*', 'sidebar_exact_route' => 'reportes.compras', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 51, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 39, 'key' => 'reportes-stock', 'label' => 'Reporte Inventario', 'icon' => 'bi-box-seam', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.stock', 'sidebar_is_route' => 'reportes.stock*', 'sidebar_exact_route' => 'reportes.stock', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 52, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 40, 'key' => 'reportes-utilidades', 'label' => 'Reporte Utilidades', 'icon' => 'bi-graph-up', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.utilidades', 'sidebar_is_route' => 'reportes.utilidades*', 'sidebar_exact_route' => 'reportes.utilidades', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 53, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 41, 'key' => 'reportes-caja', 'label' => 'Reporte Caja', 'icon' => 'bi-cash-stack', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.caja', 'sidebar_is_route' => 'reportes.caja*', 'sidebar_exact_route' => 'reportes.caja', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 54, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 42, 'key' => 'reportes-restaurante', 'label' => 'Reporte Restaurante', 'icon' => 'bi-cup-straw', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.restaurante', 'sidebar_is_route' => 'reportes.restaurante*', 'sidebar_exact_route' => 'reportes.restaurante', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 55, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 43, 'key' => 'reportes-retenciones', 'label' => 'Reporte Retenciones', 'icon' => 'bi-percent', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.retenciones', 'sidebar_is_route' => 'reportes.retenciones*', 'sidebar_exact_route' => 'reportes.retenciones', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 56, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 44, 'key' => 'reportes-fiscales', 'label' => '606/607 ITBIS', 'icon' => 'bi-file-earmark-text', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.fiscales', 'sidebar_is_route' => 'reportes.fiscales*', 'sidebar_exact_route' => 'reportes.fiscales', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 57, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 45, 'key' => 'reportes-resumen', 'label' => 'Resumen Anual', 'icon' => 'bi-bar-chart-line', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.resumen', 'sidebar_is_route' => 'reportes.resumen*', 'sidebar_exact_route' => 'reportes.resumen', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 58, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 46, 'key' => 'alquileres', 'label' => 'Dashboard Alquileres', 'icon' => 'bi-building', 'categoria' => 'alquileres', 'section' => 'Otros', 'sidebar_route' => 'alquileres.index', 'sidebar_is_route' => 'alquileres.*', 'sidebar_exact_route' => 'alquileres.index', 'sidebar_url' => null, 'sidebar_permission' => 'alquileres.view', 'activo' => 1, 'orden' => 70, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 47, 'key' => 'alquileres-viviendas', 'label' => 'Viviendas', 'icon' => 'bi-house-door', 'categoria' => 'alquileres', 'section' => 'Otros', 'sidebar_route' => 'alquileres.viviendas.index', 'sidebar_is_route' => 'alquileres.viviendas.*', 'sidebar_exact_route' => 'alquileres.viviendas.index', 'sidebar_url' => null, 'sidebar_permission' => 'alquileres.viviendas', 'activo' => 1, 'orden' => 71, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 48, 'key' => 'alquileres-inquilinos', 'label' => 'Inquilinos', 'icon' => 'bi-people', 'categoria' => 'alquileres', 'section' => 'Otros', 'sidebar_route' => 'alquileres.inquilinos.index', 'sidebar_is_route' => 'alquileres.inquilinos.*', 'sidebar_exact_route' => 'alquileres.inquilinos.index', 'sidebar_url' => null, 'sidebar_permission' => 'alquileres.inquilinos', 'activo' => 1, 'orden' => 72, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 49, 'key' => 'alquileres-contratos', 'label' => 'Contratos', 'icon' => 'bi-file-earmark-text', 'categoria' => 'alquileres', 'section' => 'Otros', 'sidebar_route' => 'alquileres.contratos.index', 'sidebar_is_route' => 'alquileres.contratos.*', 'sidebar_exact_route' => 'alquileres.contratos.index', 'sidebar_url' => null, 'sidebar_permission' => 'alquileres.contratos', 'activo' => 1, 'orden' => 73, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 50, 'key' => 'alquileres-pagos', 'label' => 'Pagos de Alquiler', 'icon' => 'bi-cash-coin', 'categoria' => 'alquileres', 'section' => 'Otros', 'sidebar_route' => 'alquileres.pagos.index', 'sidebar_is_route' => 'alquileres.pagos.*', 'sidebar_exact_route' => 'alquileres.pagos.index', 'sidebar_url' => null, 'sidebar_permission' => 'alquileres.pagos', 'activo' => 1, 'orden' => 74, 'created_at' => '2026-07-01 15:04:09', 'updated_at' => '2026-07-01 15:04:09'],
            ['id' => 51, 'key' => 'reportes-gastos', 'label' => 'Reporte Gastos', 'icon' => 'bi-cash-coin', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'reportes.gastos', 'sidebar_is_route' => 'reportes.gastos*', 'sidebar_exact_route' => 'reportes.gastos', 'sidebar_url' => null, 'sidebar_permission' => null, 'activo' => 1, 'orden' => 54, 'created_at' => '2026-07-08 00:51:01', 'updated_at' => '2026-07-08 00:51:01'],
            ['id' => 52, 'key' => 'cuentas-bancarias', 'label' => 'Cuentas Bancarias', 'icon' => 'bi-bank', 'categoria' => 'configuracion', 'section' => 'Otros', 'sidebar_route' => 'cuentas-bancarias.index', 'sidebar_is_route' => 'cuentas-bancarias.*', 'sidebar_exact_route' => 'cuentas-bancarias.index', 'sidebar_url' => null, 'sidebar_permission' => 'cuentas-bancarias.view', 'activo' => 1, 'orden' => 66, 'created_at' => '2026-07-08 00:51:01', 'updated_at' => '2026-07-08 00:51:01'],
            ['id' => 53, 'key' => 'tattoo', 'label' => 'Terminal Tattoo', 'icon' => 'bi-brush', 'categoria' => 'tattoo', 'section' => 'Otros', 'sidebar_route' => 'tattoo.index', 'sidebar_is_route' => 'tattoo.*', 'sidebar_exact_route' => 'tattoo.index', 'sidebar_url' => null, 'sidebar_permission' => 'tattoo.view', 'activo' => 1, 'orden' => 80, 'created_at' => '2026-07-08 00:51:01', 'updated_at' => '2026-07-08 00:51:01'],
            ['id' => 54, 'key' => 'tattoo-artistas', 'label' => 'Artistas', 'icon' => 'bi-person-badge', 'categoria' => 'tattoo', 'section' => 'Otros', 'sidebar_route' => 'tattoo.artistas.index', 'sidebar_is_route' => 'tattoo.artistas.*', 'sidebar_exact_route' => 'tattoo.artistas.index', 'sidebar_url' => null, 'sidebar_permission' => 'tattoo.artistas', 'activo' => 1, 'orden' => 81, 'created_at' => '2026-07-08 00:51:01', 'updated_at' => '2026-07-08 00:51:01'],
            ['id' => 55, 'key' => 'tattoo-disenos', 'label' => 'Catálogo de Diseños', 'icon' => 'bi-images', 'categoria' => 'tattoo', 'section' => 'Otros', 'sidebar_route' => 'tattoo.disenos.index', 'sidebar_is_route' => 'tattoo.disenos.*', 'sidebar_exact_route' => 'tattoo.disenos.index', 'sidebar_url' => null, 'sidebar_permission' => 'tattoo.disenos', 'activo' => 1, 'orden' => 82, 'created_at' => '2026-07-08 00:51:01', 'updated_at' => '2026-07-08 00:51:01'],
            ['id' => 56, 'key' => 'tattoo-citas', 'label' => 'Citas / Agenda', 'icon' => 'bi-calendar-event', 'categoria' => 'tattoo', 'section' => 'Otros', 'sidebar_route' => 'tattoo.citas.index', 'sidebar_is_route' => 'tattoo.citas.*', 'sidebar_exact_route' => 'tattoo.citas.index', 'sidebar_url' => null, 'sidebar_permission' => 'tattoo.citas', 'activo' => 1, 'orden' => 83, 'created_at' => '2026-07-08 00:51:01', 'updated_at' => '2026-07-08 00:51:01'],
            ['id' => 57, 'key' => 'ordenes', 'label' => 'Órdenes POS', 'icon' => 'bi-receipt-cutoff', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'ordenes.index', 'sidebar_is_route' => 'ordenes.*', 'sidebar_exact_route' => 'ordenes.index', 'sidebar_url' => null, 'sidebar_permission' => 'ordenes.view', 'activo' => 1, 'orden' => 14, 'created_at' => '2026-07-09 23:46:54', 'updated_at' => '2026-07-09 23:46:54'],
            ['id' => 58, 'key' => 'ordenes-kds', 'label' => 'Pantalla Cocina (KDS)', 'icon' => 'bi-display', 'categoria' => 'operaciones', 'section' => 'Otros', 'sidebar_route' => 'kds.index', 'sidebar_is_route' => 'kds.*', 'sidebar_exact_route' => 'kds.index', 'sidebar_url' => null, 'sidebar_permission' => 'kds.view', 'activo' => 1, 'orden' => 15, 'created_at' => '2026-07-09 23:46:54', 'updated_at' => '2026-07-09 23:46:54'],
            ['id' => 59, 'key' => 'libros-ventas', 'label' => 'Libro de Ventas', 'icon' => 'bi-book', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'libros.ventas.index', 'sidebar_is_route' => 'libros.ventas*', 'sidebar_exact_route' => 'libros.ventas.index', 'sidebar_url' => null, 'sidebar_permission' => 'reportes.view', 'activo' => 1, 'orden' => 59, 'created_at' => '2026-07-21 16:42:58', 'updated_at' => '2026-07-22 00:04:12'],
            ['id' => 60, 'key' => 'libros-compras', 'label' => 'Libro de Compras', 'icon' => 'bi-book-half', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'libros.compras.index', 'sidebar_is_route' => 'libros.compras*', 'sidebar_exact_route' => 'libros.compras.index', 'sidebar_url' => null, 'sidebar_permission' => 'reportes.view', 'activo' => 1, 'orden' => 60, 'created_at' => '2026-07-21 16:42:58', 'updated_at' => '2026-07-22 00:04:12'],
            ['id' => 61, 'key' => 'formulario-14-14', 'label' => 'Formulario 14-14', 'icon' => 'bi-file-earmark-text', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'formulario.14-14.index', 'sidebar_is_route' => 'formulario.14-14*', 'sidebar_exact_route' => 'formulario.14-14.index', 'sidebar_url' => null, 'sidebar_permission' => 'reportes.view', 'activo' => 1, 'orden' => 61, 'created_at' => '2026-07-21 16:42:58', 'updated_at' => '2026-07-22 00:04:12'],
            ['id' => 62, 'key' => 'climatizacion', 'label' => 'Dashboard Climatización', 'icon' => 'bi-wind', 'categoria' => 'climatizacion', 'section' => 'Otros', 'sidebar_route' => 'climatizacion.dashboard', 'sidebar_is_route' => 'climatizacion.dashboard', 'sidebar_exact_route' => 'climatizacion.dashboard', 'sidebar_url' => null, 'sidebar_permission' => 'climatizacion.view', 'activo' => 1, 'orden' => 90, 'created_at' => '2026-07-22 23:35:58', 'updated_at' => '2026-07-22 23:35:58'],
            ['id' => 63, 'key' => 'climatizacion-tipos-equipos', 'label' => 'Tipos de Equipo', 'icon' => 'bi-cpu', 'categoria' => 'climatizacion', 'section' => 'Otros', 'sidebar_route' => 'climatizacion.tipos-equipos.index', 'sidebar_is_route' => 'climatizacion.tipos-equipos.*', 'sidebar_exact_route' => 'climatizacion.tipos-equipos.index', 'sidebar_url' => null, 'sidebar_permission' => 'tipos-equipos.view', 'activo' => 1, 'orden' => 91, 'created_at' => '2026-07-22 23:35:58', 'updated_at' => '2026-07-22 23:35:58'],
            ['id' => 64, 'key' => 'climatizacion-instalaciones', 'label' => 'Instalaciones', 'icon' => 'bi-tools', 'categoria' => 'climatizacion', 'section' => 'Otros', 'sidebar_route' => 'climatizacion.instalaciones.index', 'sidebar_is_route' => 'climatizacion.instalaciones.*', 'sidebar_exact_route' => 'climatizacion.instalaciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'instalaciones.view', 'activo' => 1, 'orden' => 92, 'created_at' => '2026-07-22 23:35:58', 'updated_at' => '2026-07-22 23:35:58'],
            ['id' => 65, 'key' => 'climatizacion-contratos', 'label' => 'Contratos', 'icon' => 'bi-file-earmark-text', 'categoria' => 'climatizacion', 'section' => 'Otros', 'sidebar_route' => 'climatizacion.contratos.index', 'sidebar_is_route' => 'climatizacion.contratos.*', 'sidebar_exact_route' => 'climatizacion.contratos.index', 'sidebar_url' => null, 'sidebar_permission' => 'contratos.view', 'activo' => 1, 'orden' => 93, 'created_at' => '2026-07-22 23:35:58', 'updated_at' => '2026-07-22 23:35:58'],
            ['id' => 66, 'key' => 'climatizacion-mantenimientos', 'label' => 'Mantenimientos', 'icon' => 'bi-wrench-adjustable', 'categoria' => 'climatizacion', 'section' => 'Otros', 'sidebar_route' => 'climatizacion.mantenimientos.index', 'sidebar_is_route' => 'climatizacion.mantenimientos.*', 'sidebar_exact_route' => 'climatizacion.mantenimientos.index', 'sidebar_url' => null, 'sidebar_permission' => 'mantenimientos.view', 'activo' => 1, 'orden' => 94, 'created_at' => '2026-07-22 23:35:58', 'updated_at' => '2026-07-22 23:35:58'],
            ['id' => 67, 'key' => 'climatizacion-ordenes-emergencia', 'label' => 'Emergencias', 'icon' => 'bi-exclamation-octagon', 'categoria' => 'climatizacion', 'section' => 'Otros', 'sidebar_route' => 'climatizacion.ordenes-emergencia.index', 'sidebar_is_route' => 'climatizacion.ordenes-emergencia.*', 'sidebar_exact_route' => 'climatizacion.ordenes-emergencia.index', 'sidebar_url' => null, 'sidebar_permission' => 'ordenes-emergencia.view', 'activo' => 1, 'orden' => 95, 'created_at' => '2026-07-22 23:35:58', 'updated_at' => '2026-07-22 23:35:58'],
            ['id' => 68, 'key' => 'climatizacion-garantias', 'label' => 'Garantías', 'icon' => 'bi-ticket-perforated', 'categoria' => 'climatizacion', 'section' => 'Otros', 'sidebar_route' => 'climatizacion.tickets-garantia.index', 'sidebar_is_route' => 'climatizacion.tickets-garantia.*', 'sidebar_exact_route' => 'climatizacion.tickets-garantia.index', 'sidebar_url' => null, 'sidebar_permission' => 'garantias.view', 'activo' => 1, 'orden' => 96, 'created_at' => '2026-07-22 23:35:58', 'updated_at' => '2026-07-22 23:35:58'],
            ['id' => 69, 'key' => 'tecnologia', 'label' => 'Dashboard Tecnología', 'icon' => 'bi-phone', 'categoria' => 'tecnologia', 'section' => 'Otros', 'sidebar_route' => 'tecnologia.dashboard', 'sidebar_is_route' => 'tecnologia.dashboard', 'sidebar_exact_route' => 'tecnologia.dashboard', 'sidebar_url' => null, 'sidebar_permission' => 'tecnologia.view', 'activo' => 1, 'orden' => 100, 'created_at' => '2026-07-22 23:36:25', 'updated_at' => '2026-07-22 23:36:25'],
            ['id' => 70, 'key' => 'equipos', 'label' => 'Equipos (IMEI)', 'icon' => 'bi-phone', 'categoria' => 'tecnologia', 'section' => 'Otros', 'sidebar_route' => 'equipos.index', 'sidebar_is_route' => 'equipos.*', 'sidebar_exact_route' => 'equipos.index', 'sidebar_url' => null, 'sidebar_permission' => 'equipos.view', 'activo' => 1, 'orden' => 101, 'created_at' => '2026-07-22 23:36:25', 'updated_at' => '2026-07-22 23:36:25'],
            ['id' => 71, 'key' => 'tecnicas', 'label' => 'Órdenes Técnicas', 'icon' => 'bi-tools', 'categoria' => 'tecnologia', 'section' => 'Otros', 'sidebar_route' => 'tecnicas.index', 'sidebar_is_route' => 'tecnicas.*', 'sidebar_exact_route' => 'tecnicas.index', 'sidebar_url' => null, 'sidebar_permission' => 'tecnicas.view', 'activo' => 1, 'orden' => 102, 'created_at' => '2026-07-22 23:36:25', 'updated_at' => '2026-07-22 23:36:25'],
            ['id' => 72, 'key' => 'tecnicos', 'label' => 'Técnicos', 'icon' => 'bi-person-gear', 'categoria' => 'tecnologia', 'section' => 'Otros', 'sidebar_route' => 'tecnicos.index', 'sidebar_is_route' => 'tecnicos.*', 'sidebar_exact_route' => 'tecnicos.index', 'sidebar_url' => null, 'sidebar_permission' => 'tecnicos.view', 'activo' => 1, 'orden' => 103, 'created_at' => '2026-07-22 23:36:25', 'updated_at' => '2026-07-22 23:36:25'],
            ['id' => 73, 'key' => 'domotica', 'label' => 'Domótica', 'icon' => 'bi-houses', 'categoria' => 'tecnologia', 'section' => 'Otros', 'sidebar_route' => 'domotica.index', 'sidebar_is_route' => 'domotica.*', 'sidebar_exact_route' => 'domotica.index', 'sidebar_url' => null, 'sidebar_permission' => 'domotica.view', 'activo' => 1, 'orden' => 104, 'created_at' => '2026-07-22 23:36:25', 'updated_at' => '2026-07-22 23:36:25'],
            ['id' => 74, 'key' => 'garantias', 'label' => 'Garantías', 'icon' => 'bi-shield-check', 'categoria' => 'tecnologia', 'section' => 'Otros', 'sidebar_route' => 'garantias.index', 'sidebar_is_route' => 'garantias.*', 'sidebar_exact_route' => 'garantias.index', 'sidebar_url' => null, 'sidebar_permission' => 'garantias.view', 'activo' => 1, 'orden' => 105, 'created_at' => '2026-07-22 23:36:25', 'updated_at' => '2026-07-22 23:36:25'],
            ['id' => 75, 'key' => 'libros-retenciones', 'label' => 'Libro de Retenciones', 'icon' => 'bi-percent', 'categoria' => 'reportes', 'section' => 'Otros', 'sidebar_route' => 'libros-retenciones.index', 'sidebar_is_route' => 'libros-retenciones*', 'sidebar_exact_route' => 'libros-retenciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'reportes.view', 'activo' => 1, 'orden' => 61, 'created_at' => '2026-08-04 16:40:53', 'updated_at' => '2026-08-04 16:40:53'],
            ['id' => 76, 'key' => 'delivery-dashboard', 'label' => 'Dashboard Delivery', 'icon' => 'bi-truck', 'categoria' => 'delivery', 'section' => 'Otros', 'sidebar_route' => 'delivery.dashboard', 'sidebar_is_route' => 'delivery.dashboard*', 'sidebar_exact_route' => 'delivery.dashboard', 'sidebar_url' => null, 'sidebar_permission' => 'delivery-dashboard.view', 'activo' => 1, 'orden' => 110, 'created_at' => '2026-08-04 16:40:53', 'updated_at' => '2026-08-04 16:40:53'],
            ['id' => 77, 'key' => 'delivery-drivers', 'label' => 'Repartidores', 'icon' => 'bi-person-badge', 'categoria' => 'delivery', 'section' => 'Otros', 'sidebar_route' => 'delivery-drivers.index', 'sidebar_is_route' => 'delivery-drivers.*', 'sidebar_exact_route' => 'delivery-drivers.index', 'sidebar_url' => null, 'sidebar_permission' => 'delivery-drivers.view', 'activo' => 1, 'orden' => 111, 'created_at' => '2026-08-04 16:40:53', 'updated_at' => '2026-08-04 16:40:53'],
            ['id' => 78, 'key' => 'delivery-zones', 'label' => 'Zonas de Cobertura', 'icon' => 'bi-geo-alt', 'categoria' => 'delivery', 'section' => 'Otros', 'sidebar_route' => 'delivery-zones.index', 'sidebar_is_route' => 'delivery-zones.*', 'sidebar_exact_route' => 'delivery-zones.index', 'sidebar_url' => null, 'sidebar_permission' => 'delivery-zones.view', 'activo' => 1, 'orden' => 112, 'created_at' => '2026-08-04 16:40:53', 'updated_at' => '2026-08-04 16:40:53'],
            ['id' => 79, 'key' => 'delivery-tracking', 'label' => 'Seguimiento de Entregas', 'icon' => 'bi-signpost-split', 'categoria' => 'delivery', 'section' => 'Otros', 'sidebar_route' => 'delivery-tracking.index', 'sidebar_is_route' => 'delivery-tracking.*', 'sidebar_exact_route' => 'delivery-tracking.index', 'sidebar_url' => null, 'sidebar_permission' => 'delivery-tracking.view', 'activo' => 1, 'orden' => 113, 'created_at' => '2026-08-04 16:40:53', 'updated_at' => '2026-08-04 16:40:53'],
            ['id' => 80, 'key' => 'delivery-earnings', 'label' => 'Ganancias Repartidores', 'icon' => 'bi-cash-coin', 'categoria' => 'delivery', 'section' => 'Otros', 'sidebar_route' => 'driver-earnings.index', 'sidebar_is_route' => 'driver-earnings.*', 'sidebar_exact_route' => 'driver-earnings.index', 'sidebar_url' => null, 'sidebar_permission' => 'delivery-earnings.view', 'activo' => 1, 'orden' => 114, 'created_at' => '2026-08-04 16:40:53', 'updated_at' => '2026-08-04 16:40:53'],
            ['id' => 81, 'key' => 'arte', 'label' => 'Galería de Arte', 'icon' => 'bi-palette', 'categoria' => 'arte', 'section' => 'Otros', 'sidebar_route' => 'arte.index', 'sidebar_is_route' => 'arte.*', 'sidebar_exact_route' => 'arte.index', 'sidebar_url' => null, 'sidebar_permission' => 'arte.view', 'activo' => 1, 'orden' => 106, 'created_at' => '2026-08-14 18:14:13', 'updated_at' => '2026-08-14 18:14:13'],
            ['id' => 82, 'key' => 'arte-obras', 'label' => 'Obras de Arte', 'icon' => 'bi-images', 'categoria' => 'arte', 'section' => 'Otros', 'sidebar_route' => 'arte.obras.index', 'sidebar_is_route' => 'arte.obras.*', 'sidebar_exact_route' => 'arte.obras.index', 'sidebar_url' => null, 'sidebar_permission' => 'arte.obras', 'activo' => 1, 'orden' => 107, 'created_at' => '2026-08-14 18:14:13', 'updated_at' => '2026-08-14 18:14:13'],
            ['id' => 83, 'key' => 'arte-artistas', 'label' => 'Artistas', 'icon' => 'bi-person-badge', 'categoria' => 'arte', 'section' => 'Otros', 'sidebar_route' => 'arte.artistas.index', 'sidebar_is_route' => 'arte.artistas.*', 'sidebar_exact_route' => 'arte.artistas.index', 'sidebar_url' => null, 'sidebar_permission' => 'arte.artistas', 'activo' => 1, 'orden' => 108, 'created_at' => '2026-08-14 18:14:13', 'updated_at' => '2026-08-14 18:14:13'],
            ['id' => 84, 'key' => 'arte-colecciones', 'label' => 'Colecciones', 'icon' => 'bi-collection', 'categoria' => 'arte', 'section' => 'Otros', 'sidebar_route' => 'arte.colecciones.index', 'sidebar_is_route' => 'arte.colecciones.*', 'sidebar_exact_route' => 'arte.colecciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'arte.colecciones', 'activo' => 1, 'orden' => 109, 'created_at' => '2026-08-14 18:14:13', 'updated_at' => '2026-08-14 18:14:13'],
            ['id' => 85, 'key' => 'arte-exhibiciones', 'label' => 'Exhibiciones', 'icon' => 'bi-easel', 'categoria' => 'arte', 'section' => 'Otros', 'sidebar_route' => 'arte.exhibiciones.index', 'sidebar_is_route' => 'arte.exhibiciones.*', 'sidebar_exact_route' => 'arte.exhibiciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'arte.exhibiciones', 'activo' => 1, 'orden' => 110, 'created_at' => '2026-08-14 18:14:13', 'updated_at' => '2026-08-14 18:14:13'],
            ['id' => 86, 'key' => 'arte-consignaciones', 'label' => 'Consignaciones', 'icon' => 'bi-arrow-left-right', 'categoria' => 'arte', 'section' => 'Otros', 'sidebar_route' => 'arte.consignaciones.index', 'sidebar_is_route' => 'arte.consignaciones.*', 'sidebar_exact_route' => 'arte.consignaciones.index', 'sidebar_url' => null, 'sidebar_permission' => 'arte.consignaciones', 'activo' => 1, 'orden' => 111, 'created_at' => '2026-08-14 18:14:13', 'updated_at' => '2026-08-14 18:14:13'],
        ];

        foreach (array_chunk($rows, 250) as $chunk) {
            DB::table('modulos')->insert($chunk);
        }

        Schema::enableForeignKeyConstraints();
    }
}
